name: CI Test

on:
  push:
    branches: [dev, 'release/**']
  pull_request:
    branches: [dev, 'release/**', 'feature/**']

jobs:
  functional-test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        - name: package install
          run: yarn install
        - name: run test
          run: yarn test
